
PYTHON?=python

all: sdist wininst

sdist: version
	$(PYTHON) setup.py build sdist

wininst: wininst32 wininst64
	ls -1 dist/*.exe

wininst32: version
	$(PYTHON) setup.py build --plat-name=win32 --cross-ver=2.7 --cross-dir=cross/python.win32-2.7 bdist_wininst --wininst-exe-path=cross/wininst

wininst64: version
	$(PYTHON) setup.py build --plat-name=win-amd64 --cross-ver=2.7 --cross-dir=cross/python.win-amd64-2.7 bdist_wininst --wininst-exe-path=cross/wininst

version:
	test -d '.git' && echo "__version__ = '`git describe --tags --always --abbrev=4`' # generated by Makefile" > src/ae/version.py || exit 0

develop: version
	#$(PYTHON) setup.py develop
	$(PYTHON) -c "import setuptools; execfile('setup.py')" develop

test: version
	#$(PYTHON) setup.py test
	$(PYTHON) -c "import setuptools; execfile('setup.py')" test

clean:
	rm -Rf build dist/ae-* ae.egg-info


.PHONY: version test clean
