
all: sdist wininst

sdist: version
	python setup.py build sdist

wininst: wininst32 wininst64
	ls -1 dist/*.exe

wininst32: version
	python setup.py cross build --cross-dir=cross/python.win32-2.7 bdist_wininst --wininst-exe-path=cross/wininst

wininst64: version
	python setup.py cross build --cross-dir=cross/python.win-amd64-2.7 bdist_wininst --wininst-exe-path=cross/wininst 

version:
	test -d '.git' && echo "__version__ = '`git describe --tags --always --abbrev=4`' # generated by Makefile" > src/ae/version.py

test: version
	#python setup.py test
	python -m doctest -v ae/event_detector.doctest.rst

clean:
	rm -Rf build dist/ae-* ae.egg-info


.PHONY: ae/version.py clean test
