#!/usr/bin/env python

from distutils.core import setup, Extension
import os.path, sys

extra_scripts = []
extra_options = {}
cmdclass = {}
if "bdist_wininst" in sys.argv:
    install_script = "ae_post_install.py"
    extra_scripts.append(install_script)
    extra_scripts.append("AEViewer.ico")
    extra_options["bdist_wininst"] = {
        "install_script": install_script,
        "user_access_control": "auto",
    }

if "cross" in sys.argv:
    sys.argv.remove("cross")
    from cross import cross_cmdclass as cmdclass

if os.path.exists(".git"):
    import subprocess
    version = subprocess.Popen(["git", "describe", "--tags"], stdout=subprocess.PIPE).communicate()[0][1:-1]
    fh = open('ae/version.py','w')
    fh.write("# generated by setup.py\nversion = {!r}\n".format(version))
    fh.close()

elif os.path.exists('ae/version.py'):
    from ae.version import version
else:
    version = "Unknown"


setup(name='ae',
      version=version,
      description='Python accoustic emission tools',
      author='Jozef Vesely',
      author_email='vesely@gjh.sk',
      url='http://github.com/jove1/ae',
      packages=['ae'],
      scripts=['AEViewer.py'] + extra_scripts,
      ext_modules=[
          Extension('ae.event_detector', 
              define_macros=[("NPY_NO_DEPRECATED_API", "NPY_1_7_API_VERSION")],
              sources=['ae/event_detector.c'],
              ),
          ],
      requires=['numpy'],
      options=extra_options,
      cmdclass=cmdclass,
      )
